version: '3'
services:
  front:
      image: nginx:latest
      ports:
          - "8000:80"
      volumes:
          - ./front/default.conf:/etc/nginx/conf.d/default.conf
          - ./front/build/:/usr/share/nginx/html/:ro
      
  back:
      build: ./back
