version: '3'
services:
    front:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./front/default.conf:/etc/nginx/conf.d/default.conf
            - ./front/build/:/usr/share/nginx/html/:ro
        
    back:
        build: ./back
        volumes:
            - ./back/:/app/:rw
        command: python manage.py runserver 0.0.0.0:9000
        ports:
        - "9000:9000"
